[project]
name = "mygram"

[[phases]]
name = "setup"
steps = [
  "apk add --no-cache postgresql-client"
]

[[phases]]
name = "build"
steps = [
  "go mod download",
  "go build -o mygram"
]

[[phases]]
name = "start"
steps = [
  "./mygram"
]

[variables]
PORT = "8080"

[services]
[services.postgres]
image = "postgres:16"
ports = [5432]
environment = {
  POSTGRES_USER = "postgres",
  POSTGRES_PASSWORD = "hysspy99",
  POSTGRES_DB = "mygram"
}

[[mounts]]
source = "."
target = "/app"
